# Site Settings
name: Abarel Studio
title: Abarel Video Production Studio
description: Abarel Studio | Top Video Production for Ads, Commercials, TV Billboards, Product Videos, Brand Videos, Animations, Social Media Videos, Explainer Videos and Video Marketing.
tags:
  - commercial
  - graphic design
  - explainer 
  - motion design
  - photography
  - social campaign
  - corporate
  - packaging
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Gellery
    url: /photo
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: studio@abarel.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/ +Abarel use it!
formspree_form_id: xoqojnvl


# Social Media Settings
# Remove the item if you don't need it
# github_username: github_username
facebook_username: AbarelStudio
# twitter_username: twitter_username
instagram_username: abarel_studio
linkedin_username: company/abarel-studio/about/
# medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "G-EFV38LJRZ1"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: true

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [

  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md',
  'vendor'
]

# Theme
#version: v3.1.2
version: Film Studio

