name: Abarel Studio
title: Abarel | Video production company
description: Abarel is multinational company based in Kraków. Specialized in video production for companies.
tags:
  - abarel
  - video
  - animation
  - production
  - casting
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  -tittle: Gallery 
    url: /gallery
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: studio@abarel.com
# See: https://disqus.com/
disqus_username: ireneuszszandaa
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xoqojnvl
